name: "Godot Web Export"

on: 
  push:
    branches:
      - main

jobs:
  export_game:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    name: Export Game
    steps:
    - name: Checkout Source Code
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
  
    - name: Export Game using Firebelley Action
      id: export
      # Reverting back to the correct stable action release tag
      uses: firebelley/godot-export@v7.0.0
      with:
        godot_executable_download_url: "https://github.com"
        godot_export_templates_download_url: "https://github.com"
        relative_project_path: "./"  
        archive_output: true
        cache: false
        verbose: true
        use_preset_export_path: false
        export_preset_name: "Web" 

    - name: Create GitHub Release Artifact
      uses: ncipollo/release-action@v1.14.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        generateReleaseNotes: true
        tag: "build-${{ github.run_number }}"
        artifacts: ${{ steps.export.outputs.archive_directory }}/*
