name: Debug Godot

on:
  push:
    branches:
      - main

jobs:
  debug:
    runs-on: ubuntu-latest

    container:
      image: barichello/godot-ci:4.6

    steps:
      - uses: actions/checkout@v4

      - name: Show Files
        run: |
          pwd
          ls
          ls -R

      - name: Check Godot Version
        run: godot --version

      - name: Try Headless Import
        run: godot --headless --verbose --quit